### ISSUE TITLE
Can't download YouTube videos. "YouTube video not found"

### ISSUE THREAD

**Issue by LugicoHDPlayer** [tariibaba/beveldm#7]
Whenever i try to download a YouTube video it just results in an error message saying "YouTube video not found". I tried different videos, all leading to the same error.

![image](https://user-images.githubusercontent.com/29956474/105568723-e4eb1f80-5d3b-11eb-97ca-96f45631d197.png)
![image](https://user-images.githubusercontent.com/29956474/105568720-e288c580-5d3b-11eb-9029-9fb2dcb56169.png)

**Comment by tariibaba** [comment]
Hello @LugicoHDPlayer, thanks for taking the time to contribute!

We've noted this, and we're working to fix it.
